# Generated by Django 5.2.7 on 2025-12-17 22:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Caisse name (e.g., 'Caisse 1', 'Main Entrance')", max_length=100)),
                ('email', models.EmailField(help_text='Login email for caisse operator', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Hashed password', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this caisse is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses', to='events.event')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['event', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10)),
                ('item_type', models.CharField(choices=[('atelier', 'Atelier/Workshop'), ('dinner', 'Dinner/Meal'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_items', to='events.event')),
                ('session', models.ForeignKey(blank=True, help_text='Link to session if this is an atelier payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_items', to='events.session')),
            ],
            options={
                'verbose_name': 'Payable Item',
                'verbose_name_plural': 'Payable Items',
                'ordering': ['event', 'item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaisseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or reasons for cancellation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, help_text='Who cancelled this transaction', max_length=200)),
                ('marked_present', models.BooleanField(default=True, help_text='Whether participant was marked as present')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='caisse.caisse')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisse_transactions', to='events.participant')),
                ('items', models.ManyToManyField(related_name='transactions', to='caisse.payableitem')),
            ],
            options={
                'verbose_name': 'Caisse Transaction',
                'verbose_name_plural': 'Caisse Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='caisse',
            index=models.Index(fields=['event', 'is_active'], name='caisse_cais_event_i_30319e_idx'),
        ),
        migrations.AddIndex(
            model_name='caisse',
            index=models.Index(fields=['email'], name='caisse_cais_email_893e93_idx'),
        ),
        migrations.AddIndex(
            model_name='payableitem',
            index=models.Index(fields=['event', 'is_active'], name='caisse_paya_event_i_c57004_idx'),
        ),
        migrations.AddIndex(
            model_name='payableitem',
            index=models.Index(fields=['item_type'], name='caisse_paya_item_ty_1a59b0_idx'),
        ),
        migrations.AddIndex(
            model_name='caissetransaction',
            index=models.Index(fields=['caisse', 'status', '-created_at'], name='caisse_cais_caisse__a0d154_idx'),
        ),
        migrations.AddIndex(
            model_name='caissetransaction',
            index=models.Index(fields=['participant', '-created_at'], name='caisse_cais_partici_328071_idx'),
        ),
        migrations.AddIndex(
            model_name='caissetransaction',
            index=models.Index(fields=['-created_at'], name='caisse_cais_created_ffadac_idx'),
        ),
    ]
