# Generated by Django 5.2.7 on 2025-12-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_add_aggregation_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caisse',
            name='caisse_event_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='caissetransaction',
            name='transaction_caisse_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='caissetransaction',
            name='transaction_participant_idx',
        ),
        migrations.RemoveIndex(
            model_name='caissetransaction',
            name='transaction_caisse_total_idx',
        ),
        migrations.RemoveIndex(
            model_name='caissetransaction',
            name='transaction_caisse_part_idx',
        ),
        migrations.RemoveIndex(
            model_name='caissetransaction',
            name='transaction_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='payableitem',
            name='payableitem_event_type_idx',
        ),
    ]
