# Generated by Django 6.0.3 on 2026-04-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_remove_caisse_caisse_event_name_idx_and_more'),
        ('events', '0018_session_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableitem',
            name='item_type',
            field=models.CharField(choices=[('session', 'Session/Workshop'), ('dinner', 'Dinner/Meal'), ('access', 'Access/Entry'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='payableitem',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Link to session if this is a session payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_items', to='events.session'),
        ),
    ]
