# Generated by Django 5.2.7 on 2025-12-18 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_remove_event_event_status_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for easy identification', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line', max_length=300)),
                ('body', models.TextField(help_text='Email body content (supports HTML)')),
                ('description', models.TextField(blank=True, help_text='Internal description of template purpose')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customized template name', max_length=200)),
                ('subject', models.CharField(help_text='Customized email subject', max_length=300)),
                ('body', models.TextField(help_text='Customized email body (supports HTML)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_template', models.ForeignKey(blank=True, help_text='Original template this was based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_customizations', to='dashboard.emailtemplate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_email_templates', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Email Template',
                'verbose_name_plural': 'Event Email Templates',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('target_type', models.CharField(choices=[('all_participants', 'All Event Participants'), ('attended', 'Participants Who Attended'), ('not_attended', 'Participants Who Did Not Attend'), ('paid', 'Participants Who Paid'), ('not_paid', 'Participants Who Did Not Pay'), ('custom', 'Custom Selection')], max_length=50)),
                ('recipient_count', models.IntegerField(default=0, help_text='Number of recipients')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_count', models.IntegerField(default=0, help_text='Number successfully sent')),
                ('failed_count', models.IntegerField(default=0, help_text='Number failed to send')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='events.event')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_emails', to='events.participant')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dashboard.eventemailtemplate')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
