# Generated by Django 5.2.7 on 2026-01-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(blank=True, help_text='Visual builder HTML output'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='builder_config',
            field=models.JSONField(blank=True, default=dict, help_text='Visual email builder configuration'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('follow_up', 'Follow-up'), ('announcement', 'Announcement'), ('custom', 'Custom')], default='custom', help_text='Type of email template', max_length=20),
        ),
        migrations.AddField(
            model_name='eventemailtemplate',
            name='body_html',
            field=models.TextField(blank=True, help_text='Visual builder HTML output'),
        ),
        migrations.AddField(
            model_name='eventemailtemplate',
            name='builder_config',
            field=models.JSONField(blank=True, default=dict, help_text='Visual email builder configuration'),
        ),
        migrations.AddField(
            model_name='eventemailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventemailtemplate',
            name='template_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('follow_up', 'Follow-up'), ('announcement', 'Announcement'), ('registration_confirmation', 'Registration Confirmation'), ('custom', 'Custom')], default='custom', help_text='Type of email template', max_length=30),
        ),
    ]
