# Generated by Django 5.2.7 on 2026-01-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_formconfiguration_formsubmission'),
        ('events', '0013_event_registration_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='template',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='For test emails', max_length=200),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='template_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Sender email address (leave blank to use default)', max_length=200),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='events.event'),
        ),
    ]
