# Generated by Django 5.2.7 on 2026-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_emaillog_template_emaillog_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfiguration',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional banner image for the form. If not set, will use event banner if form is linked to an event.', null=True, upload_to='forms/banners/'),
        ),
    ]
