# Generated by Django 5.2.7 on 2026-01-28 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_formconfiguration_banner_image'),
        ('events', '0013_event_registration_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal campaign name', max_length=255)),
                ('subject', models.CharField(max_length=300)),
                ('from_email', models.EmailField(max_length=200)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('reply_to', models.EmailField(blank=True, max_length=200)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True, help_text='Plain text version')),
                ('track_opens', models.BooleanField(default=True, help_text='Track email opens')),
                ('track_clicks', models.BooleanField(default=True, help_text='Track link clicks')),
                ('recipient_count', models.IntegerField(default=0)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('unique_opens', models.IntegerField(default=0)),
                ('unique_clicks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.emailtemplate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='events.event')),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.TextField()),
                ('tracking_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('unique_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_links', to='dashboard.emailcampaign')),
            ],
            options={
                'verbose_name': 'Email Link',
                'verbose_name_plural': 'Email Links',
                'ordering': ['-total_clicks'],
                'unique_together': {('campaign', 'original_url')},
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('tracking_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='dashboard.emailcampaign')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.participant')),
            ],
            options={
                'verbose_name': 'Email Recipient',
                'verbose_name_plural': 'Email Recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailOpen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='dashboard.emailrecipient')),
            ],
            options={
                'verbose_name': 'Email Open',
                'verbose_name_plural': 'Email Opens',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='dashboard.emaillink')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='dashboard.emailrecipient')),
            ],
            options={
                'verbose_name': 'Email Click',
                'verbose_name_plural': 'Email Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0, help_text='Total number of form views')),
                ('unique_views', models.IntegerField(default=0, help_text='Unique visitors')),
                ('total_submissions', models.IntegerField(default=0)),
                ('completed_submissions', models.IntegerField(default=0)),
                ('abandoned_submissions', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Percentage of views that resulted in submissions')),
                ('average_completion_time', models.IntegerField(default=0, help_text='Average time to complete form in seconds')),
                ('field_analytics', models.JSONField(blank=True, default=dict)),
                ('traffic_sources', models.JSONField(blank=True, default=dict, help_text='Breakdown of traffic sources')),
                ('device_breakdown', models.JSONField(blank=True, default=dict)),
                ('browser_breakdown', models.JSONField(blank=True, default=dict)),
                ('hourly_stats', models.JSONField(blank=True, default=dict, help_text='Submissions by hour')),
                ('daily_stats', models.JSONField(blank=True, default=dict, help_text='Submissions by day')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='dashboard.formconfiguration')),
            ],
            options={
                'verbose_name': 'Form Analytics',
                'verbose_name_plural': 'Form Analytics',
            },
        ),
        migrations.CreateModel(
            name='FormView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('referer', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('time_on_page', models.IntegerField(default=0, help_text='Time spent on form in seconds')),
                ('fields_interacted', models.JSONField(default=list, help_text='List of field names user interacted with')),
                ('completed', models.BooleanField(default=False, help_text='Did user submit the form')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='dashboard.formconfiguration')),
            ],
            options={
                'verbose_name': 'Form View',
                'verbose_name_plural': 'Form Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('focused_at', models.DateTimeField(blank=True, null=True)),
                ('blurred_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent on this field in seconds')),
                ('initial_value', models.TextField(blank=True)),
                ('final_value', models.TextField(blank=True)),
                ('changes_count', models.IntegerField(default=0, help_text='Number of times value was changed')),
                ('completed', models.BooleanField(default=False, help_text='Did user complete this field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_interactions', to='dashboard.formview')),
            ],
            options={
                'verbose_name': 'Form Field Interaction',
                'verbose_name_plural': 'Form Field Interactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['campaign', 'status'], name='dashboard_e_campaig_135fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['tracking_token'], name='dashboard_e_trackin_cf0202_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailrecipient',
            unique_together={('campaign', 'email')},
        ),
        migrations.AddIndex(
            model_name='emailopen',
            index=models.Index(fields=['recipient', 'opened_at'], name='dashboard_e_recipie_96bf88_idx'),
        ),
        migrations.AddIndex(
            model_name='emailclick',
            index=models.Index(fields=['recipient', 'link'], name='dashboard_e_recipie_33b358_idx'),
        ),
        migrations.AddIndex(
            model_name='emailclick',
            index=models.Index(fields=['clicked_at'], name='dashboard_e_clicked_26b8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='formview',
            index=models.Index(fields=['form', 'session_id'], name='dashboard_f_form_id_a5f84c_idx'),
        ),
        migrations.AddIndex(
            model_name='formview',
            index=models.Index(fields=['viewed_at'], name='dashboard_f_viewed__b27278_idx'),
        ),
    ]
