# Generated by Django 5.2.7 on 2026-01-30 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_emailcampaign_emaillink_emailrecipient_emailopen_and_more'),
        ('events', '0013_event_registration_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPosterSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10, verbose_name='Genre')),
                ('grade', models.CharField(choices=[('professeur', 'Professeur'), ('maitre_de_conference', 'Maître de conférence'), ('maitre_assistant', 'Maître assistant'), ('specialiste', 'Spécialiste'), ('resident', 'Résident'), ('doctorant', 'Doctorant'), ('autre', 'Autre')], max_length=50, verbose_name='Grade')),
                ('grade_autre', models.CharField(blank=True, max_length=100, verbose_name='Autre grade (si autre)')),
                ('service', models.CharField(max_length=200, verbose_name='Service')),
                ('etablissement', models.CharField(max_length=200, verbose_name='Établissement')),
                ('wilaya', models.CharField(max_length=100, verbose_name='Wilaya')),
                ('type_participation', models.CharField(choices=[('communication_orale', 'Communication Orale'), ('poster', 'Poster'), ('e_poster', 'E-Poster')], max_length=30, verbose_name='Type de participation')),
                ('theme', models.CharField(max_length=300, verbose_name='Thème')),
                ('titre_travail', models.CharField(max_length=500, verbose_name='Titre du travail')),
                ('auteurs', models.JSONField(default=list, verbose_name='Liste des auteurs')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('materiels_methodes', models.TextField(verbose_name='Matériels et méthodes')),
                ('resultats', models.TextField(verbose_name='Résultats')),
                ('conclusion', models.TextField(verbose_name='Conclusion')),
                ('fichier_resume', models.FileField(blank=True, null=True, upload_to='eposters/resumes/', verbose_name='Fichier résumé (optionnel)')),
                ('fichier_poster', models.FileField(blank=True, null=True, upload_to='eposters/posters/', verbose_name='Fichier poster (optionnel)')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('revision_requested', 'Révision demandée')], default='pending', max_length=20)),
                ('validations_required', models.IntegerField(default=1, verbose_name='Nombre de validations requises')),
                ('final_decision_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('acceptance_email_sent', models.BooleanField(default=False)),
                ('rejection_email_sent', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eposter_submissions', to='events.event')),
                ('final_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eposter_final_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ePoster Submission',
                'verbose_name_plural': 'ePoster Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EPosterValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(verbose_name='Approuvé')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Note (1-5)')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eposter_validations', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='dashboard.epostersubmission')),
            ],
            options={
                'verbose_name': 'ePoster Validation',
                'verbose_name_plural': 'ePoster Validations',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.CreateModel(
            name='EPosterCommitteeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Membre'), ('president', 'Président du comité'), ('secretary', 'Secrétaire')], default='member', max_length=20)),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Spécialité')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eposter_committee_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eposter_committee_members', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eposter_committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ePoster Committee Member',
                'verbose_name_plural': 'ePoster Committee Members',
                'ordering': ['-assigned_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EPosterEmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('submission_received', 'Soumission reçue'), ('accepted', 'Acceptation'), ('rejected', 'Rejet'), ('revision_requested', 'Révision demandée')], max_length=30)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField(help_text='HTML content with placeholders: {{nom}}, {{prenom}}, {{titre}}, {{event_name}}')),
                ('body_text', models.TextField(blank=True, help_text='Plain text version (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eposter_email_templates', to='events.event')),
            ],
            options={
                'verbose_name': 'ePoster Email Template',
                'verbose_name_plural': 'ePoster Email Templates',
                'ordering': ['template_type'],
                'unique_together': {('event', 'template_type')},
            },
        ),
        migrations.AddIndex(
            model_name='epostersubmission',
            index=models.Index(fields=['event', 'status', '-submitted_at'], name='dashboard_e_event_i_1adafd_idx'),
        ),
        migrations.AddIndex(
            model_name='epostersubmission',
            index=models.Index(fields=['email'], name='dashboard_e_email_c0d3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='epostersubmission',
            index=models.Index(fields=['status'], name='dashboard_e_status_241e25_idx'),
        ),
        migrations.AddIndex(
            model_name='epostervalidation',
            index=models.Index(fields=['submission', 'is_approved'], name='dashboard_e_submiss_7f6d79_idx'),
        ),
        migrations.AddIndex(
            model_name='epostervalidation',
            index=models.Index(fields=['committee_member', '-validated_at'], name='dashboard_e_committ_792c26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='epostervalidation',
            unique_together={('submission', 'committee_member')},
        ),
    ]
