# Generated by Django 5.2.7 on 2026-01-30 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_epostersubmission_epostervalidation_and_more'),
        ('events', '0013_event_registration_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_type', models.CharField(choices=[('participant', 'Participant Registration Form'), ('communicant', 'Call for Communicants Form')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, help_text='Custom form title (optional)', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Form description/instructions')),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('allow_late_submissions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_configurations', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Form Configuration',
                'verbose_name_plural': 'Event Form Configurations',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'form_type')},
            },
        ),
    ]
