# Generated by Django 5.2.7 on 2026-01-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_event_form_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfiguration',
            name='countdown_date',
            field=models.DateTimeField(blank=True, help_text='Target date for countdown timer', null=True),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='countdown_enabled',
            field=models.BooleanField(default=False, help_text='Enable countdown timer on form page'),
        ),
        migrations.AddField(
            model_name='formconfiguration',
            name='countdown_title',
            field=models.CharField(blank=True, default='Event Starts In', help_text='Title to display above countdown', max_length=255),
        ),
    ]
