# Generated by Django 6.0.3 on 2026-04-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_builder_config_to_campaign'),
        ('dashboard', '0009_formconfiguration_countdown_date_and_more'),
    ]

    operations = [
    ]
