# Generated by Django 6.0.3 on 2026-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_add_brevo_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailrecipient',
            new_name='dashboard_e_externa_61772c_idx',
            old_name='dashboard_e_externa_idx',
        ),
        migrations.RemoveField(
            model_name='eposteremailtemplate',
            name='design_json',
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='builder_config',
            field=models.JSONField(blank=True, help_text='Unlayer editor design JSON', null=True),
        ),
    ]
