# Generated by Django 6.0.3 on 2026-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_dashboard_e_externa_idx_dashboard_e_externa_61772c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eposteremailtemplate',
            name='design_json',
            field=models.JSONField(blank=True, default=dict, help_text='Unlayer editor design JSON'),
        ),
    ]
