# Generated by Django 6.0.3 on 2026-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_emailcampaign_external_campaign_id_and_more'),
        ('events', '0030_alter_participant_qr_code_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='external_campaign_id',
            field=models.CharField(blank=True, help_text='Brevo campaign ID', max_length=100),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='clicks_count',
            field=models.IntegerField(default=0, help_text='Total clicks count'),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='external_id',
            field=models.CharField(blank=True, help_text='Brevo contact ID', max_length=100),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='opens_count',
            field=models.IntegerField(default=0, help_text='Total opens count'),
        ),
        migrations.AlterField(
            model_name='eposteremailtemplate',
            name='body_html',
            field=models.TextField(help_text='HTML content with placeholders: {{nom}}, {{prenom}}, {{titre}}, {{event_name}}, {{event_location}}, {{event_start_date}}, {{event_end_date}}'),
        ),
        migrations.AlterField(
            model_name='eposteremailtemplate',
            name='template_type',
            field=models.CharField(choices=[('accepted', 'Acceptation'), ('rejected', 'Rejet')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['external_id'], name='dashboard_e_externa_61772c_idx'),
        ),
    ]
