# Generated by Django 6.0.3 on 2026-05-14 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_add_eposter_final_submission_safe'),
        ('events', '0032_alter_exposantscan_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPosterFinalSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('specialite', models.CharField(choices=[('allerologie', 'Allerologie'), ('anatomique', 'Anatomique'), ('anesthesiologie', 'Anesthésiologie'), ('biologie', 'Biologie'), ('chirurgie_cardiaque', 'Chirurgie cardiaque'), ('dermatologie', 'Dermatologie'), ('diabetologie_endocrinologie', 'Diabétologie endocrinologie'), ('gastro_enterologie_hepatologie', 'Gastro-entérologie et hépatologie'), ('obstetrique_gynecologie', 'Obstétrique et gynécologie'), ('hematologie', 'Hématologie'), ('immunologie', 'Immunologie'), ('maladies_infectieuses', 'Maladies infectieuses'), ('medecine_travail', 'Médecine du travail'), ('medecine_interne', 'Médecine interne'), ('medecine_generale', 'Médecine générale'), ('nephrologie', 'Néphrologie'), ('oncologie', 'Oncologie'), ('ophtalmologie', 'Ophtalmologie'), ('orl', 'ORL'), ('professions_sante_alliees', 'Professions de santé alliées'), ('pediatrie', 'Pédiatrie'), ('pneumologie', 'Pneumologie'), ('pharmacie_hospitaliere', 'Pharmacie hospitalière'), ('pharmacien_officine', "Pharmacien d'officine"), ('medecine_soins_intensifs', 'Médecine de soins intensifs'), ('psychiatrie', 'Psychiatrie'), ('radiologie', 'Radiologie'), ('rhumatologie', 'Rhumatologie'), ('urologie', 'Urologie'), ('chirurgie_dentaire', 'Chirurgie dentaire'), ('chirurgie_pediatrique', 'Chirurgie pédiatrique')], max_length=100, verbose_name='Spécialité')),
                ('domaine_communication', models.CharField(choices=[('rhinologie', 'Rhinologie'), ('pathologie_cervico_facial', 'Pathologie cervico-facial'), ('thyroide_parathyroide', 'Thyroïde et parathyroïde'), ('orl_pediatrique', 'ORL pédiatrique'), ('laryngologie_trachee', 'Laryngologie trachée'), ('otologie', 'Otologie'), ('cancerologie', 'Cancérologie'), ('divers', 'Divers')], max_length=100, verbose_name='Domaine de communication')),
                ('poster_number', models.CharField(max_length=50, verbose_name='Poster N° (Code)')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('auteurs', models.TextField(verbose_name='Auteurs')),
                ('co_auteurs', models.TextField(blank=True, verbose_name='Co-auteurs')),
                ('abstract_file', models.FileField(upload_to='eposters/final_submissions/', verbose_name='Fichier Abstract (PDF)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ePoster Final Submission',
                'verbose_name_plural': 'ePoster Final Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='external_campaign_id',
            field=models.CharField(blank=True, help_text='Brevo campaign ID', max_length=100),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='clicks_count',
            field=models.IntegerField(default=0, help_text='Total clicks count'),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='external_id',
            field=models.CharField(blank=True, help_text='Brevo contact ID', max_length=100),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='opens_count',
            field=models.IntegerField(default=0, help_text='Total opens count'),
        ),
        migrations.AddField(
            model_name='epostersubmission',
            name='eposter_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code ePoster'),
        ),
        migrations.AlterField(
            model_name='eposteremailtemplate',
            name='body_html',
            field=models.TextField(help_text='HTML content with placeholders: {{nom}}, {{prenom}}, {{titre}}, {{event_name}}, {{event_location}}, {{event_start_date}}, {{event_end_date}}'),
        ),
        migrations.AlterField(
            model_name='eposteremailtemplate',
            name='template_type',
            field=models.CharField(choices=[('accepted', 'Acceptation'), ('rejected', 'Rejet')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['external_id'], name='dashboard_e_externa_61772c_idx'),
        ),
        migrations.AddField(
            model_name='eposterfinalsubmission',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eposter_final_submissions', to='events.event'),
        ),
        migrations.AddField(
            model_name='eposterfinalsubmission',
            name='original_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_submission', to='dashboard.epostersubmission', verbose_name='Soumission originale'),
        ),
        migrations.AddIndex(
            model_name='eposterfinalsubmission',
            index=models.Index(fields=['event', '-submitted_at'], name='dashboard_e_event_i_418864_idx'),
        ),
        migrations.AddIndex(
            model_name='eposterfinalsubmission',
            index=models.Index(fields=['poster_number'], name='dashboard_e_poster__f44ff8_idx'),
        ),
    ]
