# Generated by Django 6.0.3 on 2026-07-05 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_make_genre_optional'),
        ('events', '0032_alter_exposantscan_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificContributionCommitteeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Membre'), ('president', 'Président du comité'), ('secretary', 'Secrétaire')], default='member', max_length=20)),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Spécialité')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scientific Contribution Committee Member',
                'verbose_name_plural': 'Scientific Contribution Committee Members',
                'db_table': 'dashboard_epostercommitteemember',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ScientificContributionEmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('e_poster_accepted', 'E-Poster - Acceptation'), ('e_poster_rejected', 'E-Poster - Rejet'), ('communication_orale_accepted', 'Communication Orale - Acceptation'), ('communication_orale_rejected', 'Communication Orale - Rejet'), ('table_ronde_accepted', 'Table Ronde - Acceptation'), ('table_ronde_rejected', 'Table Ronde - Rejet'), ('atelier_accepted', 'Atelier - Acceptation'), ('atelier_rejected', 'Atelier - Rejet')], max_length=35)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField(help_text='HTML content with placeholders: {{nom}}, {{prenom}}, {{titre}}, {{event_name}}, {{event_location}}, {{event_start_date}}, {{event_end_date}}, {{contribution_code}}, {{final_submission_url}}, {{type_participation}}, {{show_final_submission}}')),
                ('body_text', models.TextField(blank=True, help_text='Plain text version (optional)')),
                ('design_json', models.JSONField(blank=True, default=dict, help_text='Unlayer editor design JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scientific Contribution Email Template',
                'verbose_name_plural': 'Scientific Contribution Email Templates',
                'db_table': 'dashboard_eposteremailtemplate',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='ScientificContributionFinalSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('specialite', models.CharField(choices=[('allerologie', 'Allerologie'), ('anatomique', 'Anatomique'), ('anesthesiologie', 'Anesthésiologie'), ('biologie', 'Biologie'), ('chirurgie_cardiaque', 'Chirurgie cardiaque'), ('dermatologie', 'Dermatologie'), ('diabetologie_endocrinologie', 'Diabétologie endocrinologie'), ('gastro_enterologie_hepatologie', 'Gastro-entérologie et hépatologie'), ('obstetrique_gynecologie', 'Obstétrique et gynécologie'), ('hematologie', 'Hématologie'), ('immunologie', 'Immunologie'), ('maladies_infectieuses', 'Maladies infectieuses'), ('medecine_travail', 'Médecine du travail'), ('medecine_interne', 'Médecine interne'), ('medecine_generale', 'Médecine générale'), ('nephrologie', 'Néphrologie'), ('oncologie', 'Oncologie'), ('ophtalmologie', 'Ophtalmologie'), ('orl', 'ORL'), ('professions_sante_alliees', 'Professions de santé alliées'), ('pediatrie', 'Pédiatrie'), ('pneumologie', 'Pneumologie'), ('pharmacie_hospitaliere', 'Pharmacie hospitalière'), ('pharmacien_officine', "Pharmacien d'officine"), ('medecine_soins_intensifs', 'Médecine de soins intensifs'), ('psychiatrie', 'Psychiatrie'), ('radiologie', 'Radiologie'), ('rhumatologie', 'Rhumatologie'), ('urologie', 'Urologie'), ('chirurgie_dentaire', 'Chirurgie dentaire'), ('chirurgie_pediatrique', 'Chirurgie pédiatrique')], max_length=100, verbose_name='Spécialité')),
                ('domaine_communication', models.CharField(choices=[('rhinologie', 'Rhinologie'), ('pathologie_cervico_facial', 'Pathologie cervico-facial'), ('thyroide_parathyroide', 'Thyroïde et parathyroïde'), ('orl_pediatrique', 'ORL pédiatrique'), ('laryngologie_trachee', 'Laryngologie trachée'), ('otologie', 'Otologie'), ('cancerologie', 'Cancérologie'), ('divers', 'Divers')], max_length=100, verbose_name='Domaine de communication')),
                ('contribution_number', models.CharField(db_column='poster_number', max_length=50, verbose_name='Numéro de Contribution (Code)')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('auteurs', models.TextField(verbose_name='Auteurs')),
                ('co_auteurs', models.TextField(blank=True, verbose_name='Co-auteurs')),
                ('abstract_file', models.FileField(upload_to='contributions/final_submissions/', verbose_name='Fichier Abstract (PDF)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scientific Contribution Final Submission',
                'verbose_name_plural': 'Scientific Contribution Final Submissions',
                'db_table': 'dashboard_eposterfinalsubmission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScientificContributionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('genre', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10, null=True, verbose_name='Genre')),
                ('grade', models.CharField(choices=[('professeur', 'Professeur'), ('maitre_de_conference', 'Maître de conférence'), ('maitre_assistant', 'Maître assistant'), ('specialiste', 'Spécialiste'), ('resident', 'Résident'), ('doctorant', 'Doctorant'), ('autre', 'Autre')], max_length=50, verbose_name='Grade')),
                ('grade_autre', models.CharField(blank=True, max_length=100, verbose_name='Autre grade (si autre)')),
                ('service', models.CharField(max_length=200, verbose_name='Service')),
                ('etablissement', models.CharField(max_length=200, verbose_name='Établissement')),
                ('wilaya', models.CharField(max_length=100, verbose_name='Wilaya')),
                ('type_participation', models.CharField(choices=[('e_poster', 'E-Poster'), ('communication_orale', 'Communication Orale'), ('table_ronde', 'Table Ronde'), ('atelier', 'Atelier')], max_length=30, verbose_name='Type de participation')),
                ('theme', models.CharField(max_length=300, verbose_name='Thème')),
                ('titre_travail', models.CharField(max_length=500, verbose_name='Titre du travail')),
                ('auteurs', models.JSONField(default=list, verbose_name='Liste des auteurs')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('materiels_methodes', models.TextField(verbose_name='Matériels et méthodes')),
                ('resultats', models.TextField(verbose_name='Résultats')),
                ('conclusion', models.TextField(verbose_name='Conclusion')),
                ('fichier_resume', models.FileField(blank=True, null=True, upload_to='contributions/resumes/', verbose_name='Fichier résumé (optionnel)')),
                ('fichier_poster', models.FileField(blank=True, null=True, upload_to='contributions/posters/', verbose_name='Fichier poster (optionnel)')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('revision_requested', 'Révision demandée')], default='pending', max_length=20)),
                ('validations_required', models.IntegerField(default=1, verbose_name='Nombre de validations requises')),
                ('final_decision_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('acceptance_email_sent', models.BooleanField(default=False)),
                ('rejection_email_sent', models.BooleanField(default=False)),
                ('contribution_code', models.CharField(blank=True, db_column='eposter_code', max_length=50, null=True, unique=True, verbose_name='Code de Contribution')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scientific Contribution Submission',
                'verbose_name_plural': 'Scientific Contribution Submissions',
                'db_table': 'dashboard_epostersubmission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScientificContributionValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(verbose_name='Approuvé')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Note (1-5)')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scientific Contribution Validation',
                'verbose_name_plural': 'Scientific Contribution Validations',
                'db_table': 'dashboard_epostervalidation',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='epostercommitteemember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='epostercommitteemember',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='epostercommitteemember',
            name='event',
        ),
        migrations.RemoveField(
            model_name='epostercommitteemember',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='eposteremailtemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eposteremailtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eposteremailtemplate',
            name='event',
        ),
        migrations.RemoveIndex(
            model_name='epostersubmission',
            name='dashboard_e_event_i_1adafd_idx',
        ),
        migrations.RemoveIndex(
            model_name='epostersubmission',
            name='dashboard_e_email_c0d3a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='epostersubmission',
            name='dashboard_e_status_241e25_idx',
        ),
        migrations.AlterUniqueTogether(
            name='epostervalidation',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='epostervalidation',
            name='dashboard_e_submiss_7f6d79_idx',
        ),
        migrations.RemoveIndex(
            model_name='epostervalidation',
            name='dashboard_e_committ_792c26_idx',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='external_campaign_id',
            field=models.CharField(blank=True, help_text='Brevo campaign ID', max_length=100),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='clicks_count',
            field=models.IntegerField(default=0, help_text='Total clicks count'),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='external_id',
            field=models.CharField(blank=True, help_text='Brevo contact ID', max_length=100),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='opens_count',
            field=models.IntegerField(default=0, help_text='Total opens count'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['external_id'], name='dashboard_e_externa_61772c_idx'),
        ),
        migrations.AddField(
            model_name='scientificcontributioncommitteemember',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_committee_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scientificcontributioncommitteemember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_committee_members', to='events.event'),
        ),
        migrations.AddField(
            model_name='scientificcontributioncommitteemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_committee_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scientificcontributionemailtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scientificcontributionemailtemplate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_email_templates', to='events.event'),
        ),
        migrations.AddField(
            model_name='scientificcontributionfinalsubmission',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_final_submissions', to='events.event'),
        ),
        migrations.AddField(
            model_name='scientificcontributionsubmission',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_submissions', to='events.event'),
        ),
        migrations.AddField(
            model_name='scientificcontributionsubmission',
            name='final_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eposter_final_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scientificcontributionfinalsubmission',
            name='original_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_submission', to='dashboard.scientificcontributionsubmission', verbose_name='Soumission originale'),
        ),
        migrations.AddField(
            model_name='scientificcontributionvalidation',
            name='committee_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scientificcontributionvalidation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='dashboard.scientificcontributionsubmission'),
        ),
        migrations.DeleteModel(
            name='EPosterCommitteeMember',
        ),
        migrations.DeleteModel(
            name='EPosterEmailTemplate',
        ),
        migrations.RemoveField(
            model_name='epostersubmission',
            name='event',
        ),
        migrations.RemoveField(
            model_name='epostersubmission',
            name='final_decision_by',
        ),
        migrations.RemoveField(
            model_name='epostervalidation',
            name='committee_member',
        ),
        migrations.RemoveField(
            model_name='epostervalidation',
            name='submission',
        ),
        migrations.AlterUniqueTogether(
            name='scientificcontributioncommitteemember',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='scientificcontributionemailtemplate',
            unique_together={('event', 'template_type')},
        ),
        migrations.AddIndex(
            model_name='scientificcontributionsubmission',
            index=models.Index(fields=['event', 'status', '-submitted_at'], name='dashboard_e_event_i_1adafd_idx'),
        ),
        migrations.AddIndex(
            model_name='scientificcontributionsubmission',
            index=models.Index(fields=['email'], name='dashboard_e_email_c0d3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='scientificcontributionsubmission',
            index=models.Index(fields=['status'], name='dashboard_e_status_241e25_idx'),
        ),
        migrations.AddIndex(
            model_name='scientificcontributionfinalsubmission',
            index=models.Index(fields=['event', '-submitted_at'], name='dashboard_e_event_i_418864_idx'),
        ),
        migrations.AddIndex(
            model_name='scientificcontributionfinalsubmission',
            index=models.Index(fields=['contribution_number'], name='dashboard_e_poster__f44ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='scientificcontributionvalidation',
            index=models.Index(fields=['submission', 'is_approved'], name='dashboard_e_submiss_7f6d79_idx'),
        ),
        migrations.AddIndex(
            model_name='scientificcontributionvalidation',
            index=models.Index(fields=['committee_member', '-validated_at'], name='dashboard_e_committ_792c26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scientificcontributionvalidation',
            unique_together={('submission', 'committee_member')},
        ),
        migrations.DeleteModel(
            name='EPosterSubmission',
        ),
        migrations.DeleteModel(
            name='EPosterValidation',
        ),
    ]
