services:
  - type: web
    name: makeplus-backend
    env: python
    buildCommand: |
      echo "===== CURRENT DIRECTORY ====="
      pwd
      echo "===== LISTING FILES ====="
      ls -R
      echo "===== INSTALLING REQUIREMENTS ====="
      pip install -r makeplus_api/requirements.txt
    startCommand: gunicorn makeplus_api.wsgi:application
    rootDir: .
