# Generated by Django 5.2.7 on 2025-11-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventassignment',
            name='role',
            field=models.CharField(choices=[('organisateur', 'Organisateur'), ('controlleur_des_badges', 'Contrôleur des Badges'), ('participant', 'Participant'), ('exposant', 'Exposant')], max_length=30),
        ),
    ]
