# Generated by Django 5.2.7 on 2025-11-25 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_usereventassignment_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guide_file',
            field=models.FileField(blank=True, help_text='Event guide PDF', null=True, upload_to='events/guides/'),
        ),
        migrations.AddField(
            model_name='event',
            name='president',
            field=models.ForeignKey(blank=True, help_text='Event president', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presided_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='programme_file',
            field=models.FileField(blank=True, help_text='Event programme PDF', null=True, upload_to='events/programmes/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='plan_file',
            field=models.FileField(blank=True, help_text='Plan PDF for exposants', null=True, upload_to='exposants/plans/'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Paid atelier (participants must pay)'),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for paid ateliers', max_digits=10),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('conference', 'Conférence'), ('atelier', 'Atelier')], default='conference', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='youtube_live_url',
            field=models.URLField(blank=True, help_text='YouTube live stream URL'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pas_encore', 'Pas Encore'), ('en_cours', 'En Cours'), ('termine', 'Terminé')], default='pas_encore', max_length=20),
        ),
        migrations.AlterField(
            model_name='usereventassignment',
            name='role',
            field=models.CharField(choices=[('gestionnaire_des_salles', 'Gestionnaire des Salles'), ('controlleur_des_badges', 'Contrôleur des Badges'), ('participant', 'Participant'), ('exposant', 'Exposant')], max_length=30),
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target', models.CharField(choices=[('all', 'Tous'), ('participants', 'Participants'), ('exposants', 'Exposants'), ('controlleurs', 'Contrôleurs'), ('gestionnaires', 'Gestionnaires')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_annonces', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='events.event')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'target', '-created_at'], name='events_anno_event_i_0f7ccb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExposantScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the visit')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposant_scans', to='events.event')),
                ('exposant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_participants', to='events.participant')),
                ('scanned_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposant_scans', to='events.participant')),
            ],
            options={
                'verbose_name': 'Exposant Scan',
                'verbose_name_plural': 'Exposant Scans',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['exposant', '-scanned_at'], name='events_expo_exposan_0aa9ff_idx'), models.Index(fields=['event', '-scanned_at'], name='events_expo_event_i_d6bf85_idx'), models.Index(fields=['scanned_participant', '-scanned_at'], name='events_expo_scanned_f879a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('gestionnaire_des_salles', 'Gestionnaire des Salles'), ('controlleur_des_badges', 'Contrôleur des Badges')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='events.event')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff', to='events.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Assignment',
                'verbose_name_plural': 'Room Assignments',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['user', 'room', 'start_time'], name='events_room_user_id_ef6ee6_idx'), models.Index(fields=['event', 'is_active'], name='events_room_event_i_e250c3_idx'), models.Index(fields=['room', 'start_time', 'end_time'], name='events_room_room_id_0aa108_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'En Attente'), ('paid', 'Payé'), ('free', 'Gratuit')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_accesses', to='events.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_accesses', to='events.session')),
            ],
            options={
                'verbose_name': 'Session Access',
                'verbose_name_plural': 'Session Accesses',
                'indexes': [models.Index(fields=['session', 'payment_status'], name='events_sess_session_d0337a_idx'), models.Index(fields=['participant', 'has_access'], name='events_sess_partici_9f9830_idx')],
                'unique_together': {('participant', 'session')},
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('answer_text', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.session')),
            ],
            options={
                'verbose_name': 'Session Question',
                'verbose_name_plural': 'Session Questions',
                'ordering': ['asked_at'],
                'indexes': [models.Index(fields=['session', 'asked_at'], name='events_sess_session_9170aa_idx'), models.Index(fields=['is_answered'], name='events_sess_is_answ_92c954_idx')],
            },
        ),
    ]
