# Generated by Django 5.2.7 on 2025-11-25 21:10

from django.db import migrations


def update_role_values(apps, schema_editor):
    """
    Update role 'organisateur' to 'gestionnaire_des_salles'
    """
    UserEventAssignment = apps.get_model('events', 'UserEventAssignment')
    UserEventAssignment.objects.filter(role='organisateur').update(role='gestionnaire_des_salles')


def reverse_role_values(apps, schema_editor):
    """
    Reverse: Update role 'gestionnaire_des_salles' back to 'organisateur'
    """
    UserEventAssignment = apps.get_model('events', 'UserEventAssignment')
    UserEventAssignment.objects.filter(role='gestionnaire_des_salles').update(role='organisateur')


def update_session_status_values(apps, schema_editor):
    """
    Update session statuses to French:
    - 'scheduled' -> 'pas_encore'
    - 'live' -> 'en_cours'
    - 'completed' -> 'termine'
    """
    Session = apps.get_model('events', 'Session')
    Session.objects.filter(status='scheduled').update(status='pas_encore')
    Session.objects.filter(status='live').update(status='en_cours')
    Session.objects.filter(status='completed').update(status='termine')


def reverse_session_status_values(apps, schema_editor):
    """
    Reverse: Update session statuses back to English
    """
    Session = apps.get_model('events', 'Session')
    Session.objects.filter(status='pas_encore').update(status='scheduled')
    Session.objects.filter(status='en_cours').update(status='live')
    Session.objects.filter(status='termine').update(status='completed')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_guide_file_event_president_and_more'),
    ]

    operations = [
        migrations.RunPython(update_role_values, reverse_role_values),
        migrations.RunPython(update_session_status_values, reverse_session_status_values),
    ]
