# Generated by Django 5.2.7 on 2025-12-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usereventassignment',
            options={},
        ),
    ]
