# Generated by Django 5.2.7 on 2025-12-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_performance_indexes'),
        ('events', '0007_alter_participant_options_and_more'),
    ]

    operations = [
    ]
