# Generated by Django 5.2.7 on 2025-12-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='exposantscan',
            name='scan_participant_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='participant_event_checkin_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomaccess',
            name='roomaccess_room_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_event_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_event_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_event_start_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionquestion',
            name='question_session_answer_idx',
        ),
        migrations.RemoveIndex(
            model_name='usereventassignment',
            name='assignment_event_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='usereventassignment',
            name='assignment_event_role_idx',
        ),
        migrations.AlterField(
            model_name='usereventassignment',
            name='role',
            field=models.CharField(choices=[('organisateur', 'Organisateur'), ('gestionnaire_des_salles', 'Gestionnaire des Salles'), ('controlleur_des_badges', 'Contrôleur des Badges'), ('participant', 'Participant'), ('exposant', 'Exposant')], max_length=30),
        ),
    ]
