# Generated by Django 5.2.7 on 2025-12-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_event_status_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data like profile_picture_url'),
        ),
        migrations.AddField(
            model_name='usereventassignment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data like assigned_room_id'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('conference', 'Conférence'), ('atelier', 'Atelier'), ('communication', 'Communication'), ('table_ronde', 'Table ronde'), ('lunch_symposium', 'Lunch symposium'), ('symposium', 'Symposium'), ('session_photo', 'Session photo de communication')], default='conference', max_length=20),
        ),
    ]
