# Generated by Django 5.2.7 on 2025-12-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_participant_metadata_usereventassignment_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text='Event banner image', null=True, upload_to='events/banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='Event logo image', null=True, upload_to='events/logos/'),
        ),
    ]
