# Generated by Django 5.2.7 on 2026-01-27 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_image_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_description',
            field=models.TextField(blank=True, help_text='Custom registration page description'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_enabled',
            field=models.BooleanField(default=True, help_text='Enable public registration for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fields_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for which fields are enabled/required'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Last name', max_length=100)),
                ('prenom', models.CharField(help_text='First name', max_length=100)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('telephone', models.CharField(help_text='Phone number', max_length=20)),
                ('pays', models.CharField(default='algerie', help_text='Country', max_length=100)),
                ('wilaya', models.CharField(blank=True, help_text='Wilaya (for Algeria)', max_length=100)),
                ('secteur', models.CharField(choices=[('prive', 'Privé'), ('public', 'Public')], help_text='Sector: Private or Public', max_length=20)),
                ('etablissement', models.CharField(help_text='Institution/Organization', max_length=200)),
                ('specialite', models.CharField(blank=True, help_text='Specialty/Field', max_length=200)),
                ('ateliers_selected', models.JSONField(blank=True, default=dict, help_text='Selected workshops per day')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Email confirmation status')),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('spam_score', models.IntegerField(default=0, help_text='Higher score = more likely spam')),
                ('is_spam', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='events.participant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='events_even_event_i_d645ce_idx'), models.Index(fields=['email', 'event'], name='events_even_email_a686fa_idx'), models.Index(fields=['is_confirmed'], name='events_even_is_conf_9b0900_idx'), models.Index(fields=['is_spam'], name='events_even_is_spam_9f7629_idx')],
            },
        ),
    ]
