# Generated by Django 6.0.3 on 2026-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_registration_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventassignment',
            name='role',
            field=models.CharField(choices=[('gestionnaire_des_salles', 'Gestionnaire de Salle'), ('controlleur_des_badges', 'Contrôleur'), ('exposant', 'Exposant'), ('committee', 'Committee'), ('participant', 'Participant')], max_length=30),
        ),
    ]
