# Generated by Django 6.0.3 on 2026-04-01 10:53

from django.db import migrations, transaction


def _rename_index_if_exists(cursor, old_name, new_name):
    """
    Rename an index only if the old name exists -- and tolerate the old
    name having disappeared between the check and the ALTER (another
    migration renaming the same index, or this one replaying after a fake
    rollback). This exact index is also renamed by
    0023_add_verification_models -- a duplicate op that made this race
    possible in the first place. The ALTER runs in its own savepoint: a
    failed statement poisons the rest of the enclosing (per-migration)
    transaction in Postgres, so a bare try/except here wouldn't be enough
    to let bookkeeping still record this migration as applied.
    """
    cursor.execute("SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = %s);", [old_name])
    if not cursor.fetchone()[0]:
        return
    try:
        with transaction.atomic():
            cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name};')
    except Exception:
        pass


def rename_indexes_if_exist(apps, schema_editor):
    """Safely rename indexes only if they exist"""
    from django.db import connection

    with connection.cursor() as cursor:
        _rename_index_if_exists(cursor, 'events_emai_user_id_idx', 'events_emai_user_id_b75a1f_idx')
        _rename_index_if_exists(cursor, 'events_emai_code_ha_idx', 'events_emai_code_ha_60562a_idx')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_emaillogincode'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, migrations.RunPython.noop),
    ]
