# Generated by Django 6.0.3 on 2026-04-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_emaillogincode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillogincode',
            new_name='events_emai_user_id_b75a1f_idx',
            old_name='events_emai_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillogincode',
            new_name='events_emai_code_ha_60562a_idx',
            old_name='events_emai_code_ha_idx',
        ),
    ]
