# Generated by Django 6.0.3 on 2026-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_events_emai_user_id_idx_events_emai_user_id_b75a1f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for event location', null=True),
        ),
    ]
