# Generated by Django 6.0.3 on 2026-04-01 14:01

from django.db import migrations, models


def add_location_url_if_not_exists(apps, schema_editor):
    """
    Add location_url column only if it doesn't exist.

    information_schema.columns raw SQL is Postgres-only; a fresh SQLite test
    DB already has this column from the model state, so it's safe to no-op.
    """
    from django.db import connection

    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_name = 'events_event' 
                AND column_name = 'location_url'
            );
        """)
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            cursor.execute("""
                ALTER TABLE events_event 
                ADD COLUMN location_url VARCHAR(200) NULL;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_events_emai_user_id_idx_events_emai_user_id_b75a1f_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(add_location_url_if_not_exists, migrations.RunPython.noop),
    ]
