# Generated by Django 5.2.7 on 2026-04-01 14:51

from django.db import migrations, models


def add_max_participants_if_not_exists(apps, schema_editor):
    """Add max_participants column only if it doesn't exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_name = 'events_session' 
                AND column_name = 'max_participants'
            );
        """)
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            cursor.execute("""
                ALTER TABLE events_session 
                ADD COLUMN max_participants INTEGER NULL;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_location_url'),
    ]

    operations = [
        migrations.RunPython(add_max_participants_if_not_exists, migrations.RunPython.noop),
    ]
