# Generated by Django 5.2.7 on 2026-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Maximum number of participants (leave empty for unlimited)', null=True),
        ),
    ]
