# Generated by Django - Add missing columns to EmailLoginCode

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_session_max_participants'),
    ]

    operations = [
        # Add is_used column if it doesn't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='events_emaillogincode' AND column_name='is_used'
                    ) THEN
                        ALTER TABLE events_emaillogincode 
                        ADD COLUMN is_used BOOLEAN DEFAULT FALSE NOT NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS is_used;"
        ),
        
        # Add used_at column if it doesn't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='events_emaillogincode' AND column_name='used_at'
                    ) THEN
                        ALTER TABLE events_emaillogincode 
                        ADD COLUMN used_at TIMESTAMP WITH TIME ZONE NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS used_at;"
        ),
        
        # Add ip_address column if it doesn't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='events_emaillogincode' AND column_name='ip_address'
                    ) THEN
                        ALTER TABLE events_emaillogincode 
                        ADD COLUMN ip_address INET NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS ip_address;"
        ),
        
        # Add user_agent column if it doesn't exist
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='events_emaillogincode' AND column_name='user_agent'
                    ) THEN
                        ALTER TABLE events_emaillogincode 
                        ADD COLUMN user_agent TEXT DEFAULT '';
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS user_agent;"
        ),
        
        # Create indexes if they don't exist
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS events_emai_user_id_b75a1f_idx 
                ON events_emaillogincode (user_id, event_id, is_used);
                
                CREATE INDEX IF NOT EXISTS events_emai_code_ha_idx 
                ON events_emaillogincode (code_hash);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS events_emai_user_id_b75a1f_idx;
                DROP INDEX IF EXISTS events_emai_code_ha_idx;
            """
        ),
    ]
