# Generated by Django - Add missing columns to EmailLoginCode

from django.db import migrations


FORWARD_SQL = """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='events_emaillogincode' AND column_name='is_used'
        ) THEN
            ALTER TABLE events_emaillogincode
            ADD COLUMN is_used BOOLEAN DEFAULT FALSE NOT NULL;
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='events_emaillogincode' AND column_name='used_at'
        ) THEN
            ALTER TABLE events_emaillogincode
            ADD COLUMN used_at TIMESTAMP WITH TIME ZONE NULL;
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='events_emaillogincode' AND column_name='ip_address'
        ) THEN
            ALTER TABLE events_emaillogincode
            ADD COLUMN ip_address INET NULL;
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='events_emaillogincode' AND column_name='user_agent'
        ) THEN
            ALTER TABLE events_emaillogincode
            ADD COLUMN user_agent TEXT DEFAULT '';
        END IF;
    END $$;

    DO $$
    BEGIN
        BEGIN
            CREATE INDEX events_emai_user_id_b75a1f_idx
            ON events_emaillogincode (user_id, event_id, is_used);
        EXCEPTION WHEN duplicate_table OR unique_violation THEN
            NULL;
        END;
    END $$;

    DO $$
    BEGIN
        BEGIN
            CREATE INDEX events_emai_code_ha_idx
            ON events_emaillogincode (code_hash);
        EXCEPTION WHEN duplicate_table OR unique_violation THEN
            NULL;
        END;
    END $$;
"""

REVERSE_SQL = """
    ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS is_used;
    ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS used_at;
    ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS ip_address;
    ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS user_agent;
    DROP INDEX IF EXISTS events_emai_user_id_b75a1f_idx;
    DROP INDEX IF EXISTS events_emai_code_ha_idx;
"""


def _add_missing_columns(apps, schema_editor):
    """
    Postgres-only (DO $$ PL/pgSQL blocks, INET type) — was four RunSQL ops
    that ran unconditionally regardless of backend, breaking `manage.py test`
    on the SQLite DB local dev actually uses. Same SQL, same effect on
    Postgres; a clean no-op everywhere else, where the model state already
    has these columns from CREATE TABLE.

    The two indexes used `CREATE INDEX IF NOT EXISTS` originally, which
    still raised "duplicate key value violates unique constraint
    pg_class_relname_nsp_index" on a deploy where this migration re-ran
    (this production database has repeatedly lost its django_migrations
    bookkeeping between deploys, same as the SeparateDatabaseAndState
    migrations elsewhere in this app). Switching to a `pg_indexes`
    existence check (matching the column checks above) still wasn't
    enough -- it hit the same duplicate-key error on a later deploy,
    because the check-then-create isn't atomic: something (multiple
    concurrent `migrate` invocations on Render, most likely) can pass
    the "not exists" check on two attempts before either commits, so
    both try to create the index and the second collides. Each CREATE
    INDEX is now wrapped in its own nested BEGIN/EXCEPTION and swallows
    duplicate_table/unique_violation at the point of creation itself,
    which is safe under that race regardless of what causes it.
    """
    from django.db import connection

    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        cursor.execute(FORWARD_SQL)


def _remove_missing_columns(apps, schema_editor):
    from django.db import connection

    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        cursor.execute(REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_session_max_participants'),
    ]

    operations = [
        migrations.RunPython(_add_missing_columns, _remove_missing_columns),
    ]
