# Generated by Django - Add missing columns to EmailLoginCode

from django.db import migrations


FORWARD_SQL = """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='events_emaillogincode' AND column_name='is_used'
        ) THEN
            ALTER TABLE events_emaillogincode
            ADD COLUMN is_used BOOLEAN DEFAULT FALSE NOT NULL;
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='events_emaillogincode' AND column_name='used_at'
        ) THEN
            ALTER TABLE events_emaillogincode
            ADD COLUMN used_at TIMESTAMP WITH TIME ZONE NULL;
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='events_emaillogincode' AND column_name='ip_address'
        ) THEN
            ALTER TABLE events_emaillogincode
            ADD COLUMN ip_address INET NULL;
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='events_emaillogincode' AND column_name='user_agent'
        ) THEN
            ALTER TABLE events_emaillogincode
            ADD COLUMN user_agent TEXT DEFAULT '';
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_indexes WHERE indexname = 'events_emai_user_id_b75a1f_idx'
        ) THEN
            CREATE INDEX events_emai_user_id_b75a1f_idx
            ON events_emaillogincode (user_id, event_id, is_used);
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_indexes WHERE indexname = 'events_emai_code_ha_idx'
        ) THEN
            CREATE INDEX events_emai_code_ha_idx
            ON events_emaillogincode (code_hash);
        END IF;
    END $$;
"""

REVERSE_SQL = """
    ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS is_used;
    ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS used_at;
    ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS ip_address;
    ALTER TABLE events_emaillogincode DROP COLUMN IF EXISTS user_agent;
    DROP INDEX IF EXISTS events_emai_user_id_b75a1f_idx;
    DROP INDEX IF EXISTS events_emai_code_ha_idx;
"""


def _add_missing_columns(apps, schema_editor):
    """
    Postgres-only (DO $$ PL/pgSQL blocks, INET type) — was four RunSQL ops
    that ran unconditionally regardless of backend, breaking `manage.py test`
    on the SQLite DB local dev actually uses. Same SQL, same effect on
    Postgres; a clean no-op everywhere else, where the model state already
    has these columns from CREATE TABLE.

    The two indexes used `CREATE INDEX IF NOT EXISTS` originally, which
    still raised "duplicate key value violates unique constraint
    pg_class_relname_nsp_index" on a deploy where this migration re-ran
    (this production database has repeatedly lost its django_migrations
    bookkeeping between deploys, same as the SeparateDatabaseAndState
    migrations elsewhere in this app) -- Postgres index names are unique
    per-schema, not per-table, and something about how that race played
    out defeated IF NOT EXISTS here. Switched to the same explicit
    pg_indexes existence check already used for the columns above, which
    doesn't have that failure mode.
    """
    from django.db import connection

    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        cursor.execute(FORWARD_SQL)


def _remove_missing_columns(apps, schema_editor):
    from django.db import connection

    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        cursor.execute(REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_session_max_participants'),
    ]

    operations = [
        migrations.RunPython(_add_missing_columns, _remove_missing_columns),
    ]
