# Generated by Django 6.0.3 on 2026-04-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_delete_existing_participants'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillogincode',
            new_name='events_emai_code_ha_60562a_idx',
            old_name='events_emai_code_ha_idx',
        ),
        migrations.RenameIndex(
            model_name='formregistrationverification',
            new_name='events_form_email_0391c3_idx',
            old_name='events_form_email_form_idx',
        ),
        migrations.RenameIndex(
            model_name='formregistrationverification',
            new_name='events_form_code_ha_b77569_idx',
            old_name='events_form_code_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='formregistrationverification',
            new_name='events_form_expires_959e14_idx',
            old_name='events_form_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='signupverification',
            new_name='events_sign_email_a18e44_idx',
            old_name='events_sign_email_is_used_idx',
        ),
        migrations.RenameIndex(
            model_name='signupverification',
            new_name='events_sign_code_ha_5fb7bf_idx',
            old_name='events_sign_code_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='signupverification',
            new_name='events_sign_expires_7d73df_idx',
            old_name='events_sign_expires_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for event location', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Maximum number of participants (leave empty for unlimited)', null=True),
        ),
    ]
