# Generated by Django 6.0.3 on 2026-04-30 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_allow_null_notes_exposantscan'),
        ('events', '0031_add_controller_scan_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_user_id', models.IntegerField(help_text='User ID of scanned participant')),
                ('badge_id', models.CharField(help_text='Badge ID scanned', max_length=100)),
                ('participant_name', models.CharField(help_text='Participant full name', max_length=255)),
                ('participant_email', models.EmailField(help_text='Participant email', max_length=254)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('not_registered', 'Not Registered')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if scan failed')),
                ('total_paid_items', models.IntegerField(default=0, help_text='Number of paid items at scan time')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid', max_digits=10)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='FormRegistrationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('form_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Form Registration Verification',
                'verbose_name_plural': 'Form Registration Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Event-specific data')),
            ],
        ),
        migrations.CreateModel(
            name='SignUpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('signup_data', models.JSONField(blank=True, default=dict, help_text='Temporary storage for first_name, last_name, password_hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sign Up Verification',
                'verbose_name_plural': 'Sign Up Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='events_part_event_i_218ea6_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillogincode',
            new_name='events_emai_code_ha_60562a_idx',
            old_name='events_emai_code_ha_idx',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for event location', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(default='participant', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='session',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Maximum number of participants (leave empty for unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='exposantscan',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about the visit', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controllerscan',
            name='controller',
            field=models.ForeignKey(help_text='Controller who scanned', on_delete=django.db.models.deletion.CASCADE, related_name='controller_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controllerscan',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_scans', to='events.event'),
        ),
        migrations.AddField(
            model_name='formregistrationverification',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='dashboard.formconfiguration'),
        ),
        migrations.AddField(
            model_name='participanteventregistration',
            name='allowed_rooms',
            field=models.ManyToManyField(blank=True, related_name='allowed_participants', to='events.room'),
        ),
        migrations.AddField(
            model_name='participanteventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_registrations', to='events.event'),
        ),
        migrations.AddField(
            model_name='participanteventregistration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(related_name='registered_participants', through='events.ParticipantEventRegistration', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='signupverification',
            index=models.Index(fields=['email', 'is_used', '-created_at'], name='events_sign_email_a18e44_idx'),
        ),
        migrations.AddIndex(
            model_name='signupverification',
            index=models.Index(fields=['code_hash', 'is_used'], name='events_sign_code_ha_5fb7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='signupverification',
            index=models.Index(fields=['expires_at', 'is_used'], name='events_sign_expires_7d73df_idx'),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='allowed_rooms',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='checked_in_at',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_checked_in',
        ),
        migrations.AddIndex(
            model_name='controllerscan',
            index=models.Index(fields=['controller', '-scanned_at'], name='events_cont_control_b4e68d_idx'),
        ),
        migrations.AddIndex(
            model_name='controllerscan',
            index=models.Index(fields=['event', '-scanned_at'], name='events_cont_event_i_d74a38_idx'),
        ),
        migrations.AddIndex(
            model_name='controllerscan',
            index=models.Index(fields=['controller', 'event', '-scanned_at'], name='events_cont_control_132a72_idx'),
        ),
        migrations.AddIndex(
            model_name='formregistrationverification',
            index=models.Index(fields=['email', 'form', 'is_used', '-created_at'], name='events_form_email_0391c3_idx'),
        ),
        migrations.AddIndex(
            model_name='formregistrationverification',
            index=models.Index(fields=['code_hash', 'is_used'], name='events_form_code_ha_b77569_idx'),
        ),
        migrations.AddIndex(
            model_name='formregistrationverification',
            index=models.Index(fields=['expires_at', 'is_used'], name='events_form_expires_959e14_idx'),
        ),
        migrations.AddIndex(
            model_name='participanteventregistration',
            index=models.Index(fields=['event', 'is_checked_in'], name='events_part_event_i_6a0bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='participanteventregistration',
            index=models.Index(fields=['participant', 'event'], name='events_part_partici_472b36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participanteventregistration',
            unique_together={('participant', 'event')},
        ),
    ]
